### ISSUE TITLE
Several errors in containers

### ISSUE THREAD

**Issue by esturniolo** [m0wer/mercaapi#17]
Hi!!
I discovered your repo and I tried to use it, but it has several errors in the containers
```
CONTAINER ID   IMAGE                           COMMAND                  CREATED              STATUS                                  PORTS                            NAMES
218e4050d5c3   ghcr.io/m0wer/mercaapi:master   "python -m fastapi r…"   About a minute ago   Restarting (1) Less than a second ago                                    mercaapi-app-1
ed53789a09c5   mher/flower                     "python -m celery fl…"   About a minute ago   Up 7 seconds                            0.0.0.0:5555->5555/tcp           mercaapi-flower-1
197f2061b04b   ghcr.io/m0wer/mercaapi:master   "sh -c exit"             About a minute ago   Exited (0) 7 seconds ago                                                 mercaapi-tests-1
f226a3c2bb78   mercaapi-worker-high            "python -m celery -A…"   About a minute ago   Restarting (2) Less than a second ago                                    mercaapi-worker-high-1
7ac6832431a7   mercaapi-worker-low             "python -m celery -A…"   About a minute ago   Up Less than a second                                                    mercaapi-worker-low-1
44313ebe6ff0   redis:7-alpine                  "docker-entrypoint.s…"   About a minute ago   Up 7 seconds                            0.0.0.0:6379->6379/tcp           mercaapi-redis-1
```

Do you have any idea if you will continue with this development? Thanks!!

**Comment by m0wer** [comment]
Hi @esturniolo ! Let me share my current docker-compose:

```yaml
services:
  app:
    image: ghcr.io/m0wer/mercaapi:master
    command: python -m fastapi run --reload --port 80
    volumes:
      - /data/mercaapi/db/mercadona.db:/app/mercadona.db
    environment:
      - PYTHONPATH=/app
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - worker-high
      - worker-low
    user: '1000:1000'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    env_file: stack.env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mercaapi.rule=Host(`mercaapi.sgn.space`)"
      - "traefik.http.routers.mercaapi.entrypoints=websecure"
      - "traefik.http.services.mercaapi.loadbalancer.server.port=80"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolalloworiginlist=https://mercaticket.sgn.space,http://mercaticket.sgn.space:3000"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowmethods=GET,POST,OPTIONS"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowheaders=Content-Type,Authorization"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors-headers.headers.addvaryheader=true"
      - "traefik.http.routers.mercaapi.middlewares=cors-headers@docker"

  redis:
    image: redis:7-alpine
    volumes:
      - /data/mercaapi/redis:/data
    user: '1000:1000'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    restart: always

  worker-high:
    image: ghcr.io/m0wer/mercaapi:master
    command: python -m celery -A app.worker worker -Q high -c 8 -l DEBUG
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app
    volumes:
      - /data/mercaapi/db/mercadona.db:/app/mercadona.db
    depends_on:
      - redis
    user: '1000:1000'
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 2G
    restart: always

  worker-low:
    image: ghcr.io/m0wer/mercaapi:master
    command: python -m celery -A app.worker worker -Q low -c 1 -l DEBUG
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app
    volumes:
      - /data/mercaapi/db/mercadona.db:/app/mercadona.db
    depends_on:
      - redis
    user: '1000:1000'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
    restart: always

  flower:
    image: mher/flower
    command: python -m celery flower --broker=redis://redis:6379/0 --port=5555 --basic-auth=admin:[REDACTED] --url-prefix=/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - worker-high
    user: '1000:1000'
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.rule=Host(`mercaapi.sgn.space`) && PathPrefix(`/flower`)"
      - "traefik.http.routers.flower.entrypoints=websecure"
      - "traefik.http.services.flower.loadbalancer.server.port=5555"
      - "traefik.http.middlewares.strip-flower-prefix.stripprefix.prefixes=/flower"
   ```

`.env`:
```
GEMINI_API_KEY=[REDACTED]
LOGURU_LEVEL=DEBUG
MAX_WORKERS=2
GROQ_API_KEY=gsk_[REDACTED]
```

Let me know if it works for you :-)
